-- 将手动 ID 改为自增：为线上 schema 变更审阅用
ALTER TABLE article MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE home_carousel MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE collapse_card MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE team_member MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE timeline_carousel MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE timeline_event MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE parallax_story MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE tool_site MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE music MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE called_text MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE friend_link MODIFY id BIGINT AUTO_INCREMENT;
