server:
  port: ${SERVER_PORT:8081}

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    org.hibernate.SQL: warn
